### ISSUE TITLE
use of undeclared identifier 'MTLTextureType2DMultisampleArray'

### ISSUE THREAD

**Issue by ryandesign** [KhronosGroup/MoltenVK#416]
Hi, I'm the maintainer of MoltenVK in MacPorts. I'm unable to update from 1.0.27 to a later version on macOS 10.13.6.

With 1.0.28 the error is:

```
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:708:49: error: use of undeclared identifier 'MTLTextureType2DMultisampleArray'; did you mean 'MTLTextureType2DMultisample'?
                        if (arraySize > 1 && isMultisample) { return MTLTextureType2DMultisampleArray; }
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                     MTLTextureType2DMultisample
In file included from MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:20:
In file included from MoltenVK/MoltenVK/API/mvk_datatypes.h:36:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Metal.framework/Headers/Metal.h:10:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLBlitCommandEncoder.h:13:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLTexture.h:28:5: note: 'MTLTextureType2DMultisample' declared here
    MTLTextureType2DMultisample = 4,
    ^
1 error generated.
```

With 1.0.29 the error is:

```
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:775:49: error: use of undeclared identifier 'MTLTextureType2DMultisampleArray'; did you mean 'MTLTextureType2DMultisample'?
                        if (arraySize > 1 && isMultisample) { return MTLTextureType2DMultisampleArray; }
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                     MTLTextureType2DMultisample
In file included from MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:20:
In file included from MoltenVK/MoltenVK/API/mvk_datatypes.h:36:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Metal.framework/Headers/Metal.h:10:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLBlitCommandEncoder.h:13:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLTexture.h:28:5: note: 'MTLTextureType2DMultisample' declared here
    MTLTextureType2DMultisample = 4,
    ^
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:802:24: error: use of undeclared identifier 'MTLTextureType2DMultisampleArray'; did you mean 'MTLTextureType2DMultisample'?
                return MTLTextureType2DMultisampleArray;
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       MTLTextureType2DMultisample
In file included from MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:20:
In file included from MoltenVK/MoltenVK/API/mvk_datatypes.h:36:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Metal.framework/Headers/Metal.h:10:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLBlitCommandEncoder.h:13:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLTexture.h:28:5: note: 'MTLTextureType2DMultisample' declared here
    MTLTextureType2DMultisample = 4,
    ^
2 errors generated.
```

**Comment by ryandesign** [comment]
[Apple documentation](https://developer.apple.com/documentation/metal/mtltexturetype/mtltexturetype2dmultisamplearray?language=objc) shows `MTLTextureType2DMultisampleArray` was added in macOS 10.14.

**Comment by cdavis5e** [comment]
Unfortunately, this project doesn't have a policy of maintaining SDK backwards compatibility, only binary backwards compatibility (e.g. a library compiled for 10.14 will still work on 10.11). I'm afraid you'll have to maintain patches to make this compile with Xcode 9--or require Xcode 10 in the Portfile.

**Comment by ryandesign** [comment]
It might be good if the build system could detect a too-old SDK and print a more-specific error message earlier on in the build process. If I remember correctly, I encountered the above error after I had already spent half an hour compiling. This made me think it was a bug you would want to fix.

You should also update the documentation. Currently the readme says "MoltenVK requires at least macOS 10.11 or iOS 9" (without specifying that this refers to runtime and not build time) and "Xcode 9 or above is required to build and link MoltenVK projects".

**Comment by CoreyDotCom** [comment]
@cdavis5e Please address your build instructions. You note that XCode 9 is compatible with this project but it is not given this issue that our team just hit. As in can you update to require XCode 10 or above?

**Comment by billhollings** [comment]
Sorry for the confusion. This makes sense. I'll update the docs to clarify that MoltenVK must be built with the latest version of Xcode and SDK libs.

**Comment by billhollings** [comment]
The documentation confusion is fixed in PR #498.
