### PR TITLE
Fix visionOS build

### LINKED ISSUE #2160: Failing to build for visionOS
Trying to build MoltenVK for vision OS but getting errors, with latest Xcode and SDKs.

- did a clone from git, using main branch
- built dependencies: ./fetchDependencies --visionos --macos --ios --iossim
- build for visionOS: make visionos

This produces a few deprecated API warnings, and: 

1/ a warning on MVKOSExtensions.h:70:1: warning: non-void function does not return a value.
    Seems like MVK_VISIONOS is not defined

2/ a compile error on MVKSwapchain.mm:193:35: error: property 'screenMVK' not found on
      object of type 'CAMetalLayer *'
    visionOS does support screens so that code should not be there.

Full log at https://pastebin.com/eP3jgM3Y

### PR DESCRIPTION
**Pull request by mkrus**
This adds a few macros to test which platform is currently being built. Addresses some compile warnings such as missing return values. Still a fair amount of deprecation warnings to handle.

Have not actually tested the resulting binary yet.

visionOS is also not yet enabled by default, not sure if we want to require Xcode 15 just yet and couldn't find a way of doing conditional dependencies in Xcode projects or Makefiles.

Fix #2160.

### CODE REVIEW

File: Common/MVKCommonEnvironment.h [hunk 1]
```diff
@@ -85,7 +88,17 @@ extern "C" {
 
 /** Building for macOS, iOS or visionOS. */
 #ifndef MVK_MACOS_OR_IOS_OR_VISIONOS
-#	define MVK_MACOS_OR_IOS_OR_VISIONOS	(MVK_MACOS || MVK_IOS | MVK_VISIONOS)
+#	define MVK_MACOS_OR_IOS_OR_VISIONOS	(MVK_MACOS || MVK_IOS || MVK_VISIONOS)
```
Comment (billhollings) [inline Common/MVKCommonEnvironment.h:91]: I know you didn't originally add this, but could this be removed, and `!MVK_TVOS` used instead?

File: Common/MVKCommonEnvironment.h [hunk 2]
```diff
@@ -85,7 +88,17 @@ extern "C" {
...
+#endif
+
+/** Building for iOS or visionOS. */
+#ifndef MVK_IOS_OR_VISIONOS
+#    define MVK_IOS_OR_VISIONOS    (MVK_IOS || MVK_VISIONOS)
+#endif
+
+/** Building for iOS or tvOS or visionOS. */
+#ifndef MVK_IOS_OR_TVOS_OR_VISIONOS
```
Comment (billhollings) [inline Common/MVKCommonEnvironment.h:100]: Similar to above, could this be removed, and `!MVK_MACOS` used instead?

File: MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm [hunk 3]
```diff
@@ -1007,10 +1007,12 @@
 	addVkFormatDesc( S8_UINT, Stencil8, Invalid, Invalid, Invalid, 1, 1, 1, DepthStencil );
 
 	addVkFormatDesc( D16_UNORM, Depth16Unorm, Depth32Float, Invalid, Invalid, 1, 1, 2, DepthStencil );
+#if !MVK_VISIONOS
 	addVkFormatDesc( D16_UNORM_S8_UINT, Invalid, Depth16Unorm_Stencil8, Invalid, Invalid, 1, 1, 3, DepthStencil );
 	addVkFormatDesc( D24_UNORM_S8_UINT, Depth24Unorm_Stencil8, Depth32Float_Stencil8, Invalid, Invalid, 1, 1, 4, DepthStencil );
 
-	addVkFormatDesc( X8_D24_UNORM_PACK32, Invalid, Depth24Unorm_Stencil8, Invalid, Invalid, 1, 1, 4, DepthStencil );
+    addVkFormatDesc( X8_D24_UNORM_PACK32, Invalid, Depth24Unorm_Stencil8, Invalid, Invalid, 1, 1, 4, DepthStencil );
+#endif
```
Comment (billhollings) [inline MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm:1015]: The way we handle `MTLPixelFormats` that do not exist on some platforms, is to `#define` that `MTLPixelFormat` as `MTLPixelFormatInvalid` for those platforms in a section at the top of this file.

The mapping logic of `MTLPixelFormats` then automatically handles its absence.

File: MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm [hunk 4]
```diff
@@ -1320,9 +1322,11 @@
 	addMTLPixelFormatDesc    ( Depth16Unorm, None, None, None );
 	addMTLPixelFormatDesc    ( Depth32Float, None, DRM, DRFMR );
 	addMTLPixelFormatDesc    ( Stencil8, None, DRM, DRMR );
+#if !MVK_VISIONOS
 	addMTLPixelFormatDesc    ( Depth24Unorm_Stencil8, Depth24_Stencil8, None, None );
-	addMTLPixelFormatDesc    ( Depth32Float_Stencil8, Depth32_Stencil8, DRM, DRFMR );
-	addMTLPixelFormatDesc    ( X24_Stencil8, Depth24_Stencil8, None, DRMR );
+    addMTLPixelFormatDesc    ( X24_Stencil8, Depth24_Stencil8, None, DRMR );
+#endif
+    addMTLPixelFormatDesc    ( Depth32Float_Stencil8, Depth32_Stencil8, DRM, DRFMR );
```
Comment (billhollings) [inline MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm:1329]: Ditto re missing formats.

File: MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm [hunk 5]
```diff
@@ -190,8 +190,8 @@
 VkResult MVKSwapchain::getRefreshCycleDuration(VkRefreshCycleDurationGOOGLE *pRefreshCycleDuration) {
 	if (_device->getConfigurationResult() != VK_SUCCESS) { return _device->getConfigurationResult(); }
 
-	auto* screen = getCAMetalLayer().screenMVK;		// Will be nil if headless
 #if MVK_MACOS && !MVK_MACCAT
+    auto* screen = getCAMetalLayer().screenMVK;        // Will be nil if headless
```
Comment (billhollings) [inline MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm:194]: Although the declaration might look a bit odd, it would probably be more consistent to add something like the following to `CAMetalLayer+MoltenVK.h/mm`:

`@property(nonatomic, readonly) nil screenMVK;`

File: MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm [hunk 6]
```diff
@@ -207,6 +207,7 @@
 			framesPerSecond = 60.0;
 	}
 #elif MVK_IOS_OR_TVOS || MVK_MACCAT
+    auto* screen = getCAMetalLayer().screenMVK;        // Will be nil if headless
```
Comment (billhollings) [inline MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm:210]: Ditto.

File: MoltenVKPackaging.xcodeproj/project.pbxproj [hunk 7]
```diff
@@ -278,6 +279,7 @@
 				A9C70F45221B04C800FBA31A /* create_dylib_ios.sh */,
 				A9C70F41221B04C800FBA31A /* create_dylib_macos.sh */,
 				A9FC5F64249D3778003CB086 /* create_dylib_tvos.sh */,
+				279BD8642B7FAE0A0021CE70 /* create_dylib_xros.sh */,
```
Comment (billhollings) [inline MoltenVKPackaging.xcodeproj/project.pbxproj:282]: Where is `create_dylib_xros.sh` itself?

**Review by billhollings — CHANGES_REQUESTED** [review]
Thanks for submitting this! `VisionOS` is poorly supported on MoltenVK, and this will really help.

I've requested some changes.

> visionOS is also not yet enabled by default, not sure if we want to require Xcode 15 just yet and couldn't find a way of doing conditional dependencies in Xcode projects or Makefiles.

We can't force Xcode 15 yet, so we'll probably have to leave it out of an `all` build for now. However, it would be good to add an Xcode 15 build on VisionOS to `CI.yml`. If you aren't familiar with this, I can add that later.

Fix #2160.

File: MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm (hunk 5 above)
Comment (cdavis5e) [reply MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm:194]: > ```objc
> @property(nonatomic, readonly) nil screenMVK;
> ```

That syntax doesn't work:

> ```
> test41.m:5:32: error: type name requires a specifier or qualifier
> @property(nonatomic, readonly) nil screenMVK;
>                                ^
> /usr/include/objc/./objc.h:108:16: note: expanded from macro 'nil'
> #   define nil __DARWIN_NULL
>                ^
> /usr/include/sys/_types.h:52:23: note: expanded from macro '__DARWIN_NULL'
> #define __DARWIN_NULL ((void *)0)
>                       ^
> test41.m:5:32: error: expected member name or ';' after declaration specifiers
> /usr/include/objc/./objc.h:108:16: note: expanded from macro 'nil'
> #   define nil __DARWIN_NULL
>                ^
> /usr/include/sys/_types.h:52:25: note: expanded from macro '__DARWIN_NULL'
> #define __DARWIN_NULL ((void *)0)
>                         ^
> test41.m:5:32: error: expected ')'
> /usr/include/objc/./objc.h:108:16: note: expanded from macro 'nil'
> #   define nil __DARWIN_NULL
>                ^
> /usr/include/sys/_types.h:52:25: note: expanded from macro '__DARWIN_NULL'
> #define __DARWIN_NULL ((void *)0)
>                         ^
> test41.m:5:32: note: to match this '('
> /usr/include/objc/./objc.h:108:16: note: expanded from macro 'nil'
> #   define nil __DARWIN_NULL
>                ^
> /usr/include/sys/_types.h:52:24: note: expanded from macro '__DARWIN_NULL'
> #define __DARWIN_NULL ((void *)0)
>                        ^
> test41.m:5:32: error: expected ')'
> @property(nonatomic, readonly) nil bar;
>                                ^
> /usr/include/objc/./objc.h:108:16: note: expanded from macro 'nil'
> #   define nil __DARWIN_NULL
>                ^
> /usr/include/sys/_types.h:52:32: note: expanded from macro '__DARWIN_NULL'
> #define __DARWIN_NULL ((void *)0)
>                                ^
> test41.m:5:32: note: to match this '('
> /usr/include/objc/./objc.h:108:16: note: expanded from macro 'nil'
> #   define nil __DARWIN_NULL
>                ^
> /usr/include/sys/_types.h:52:23: note: expanded from macro '__DARWIN_NULL'
> #define __DARWIN_NULL ((void *)0)
>                       ^
> test41.m:5:1: error: property requires fields to be named
> @property(nonatomic, readonly) nil screenMVK;
> ^                              ~~~
> test41.m:5:35: error: expected ';' at end of declaration list
> @property(nonatomic, readonly) nil screenMVK;
>                                   ^
>                                   ;
> test41.m:5:36: warning: type specifier missing, defaults to 'int'
>       [-Wimplicit-int]
> @property(nonatomic, readonly) nil screenMVK;
>                                    ^
> test41.m:5:36: error: cannot declare variable inside @interface or @protocol
> 1 warning and 7 errors generated.
> ```

It doesn't even work with Xcode 15.3β3.

Comment (billhollings) [reply MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm:194]: Thanks for testing. 

I haven't checked, but perhaps there is an equivalent object type in VisionOS that could be declared to be returned, even if we do return `nil`? 

If there isn't something equivalent that makes sense, we can ignore my suggestion here.

File: Common/MVKCommonEnvironment.h (hunk 1 above)
Comment (mkrus) [reply Common/MVKCommonEnvironment.h:91]: would make sense, I did find this was getting out of hand. I suppose new platform don't get added very often but seems like a brittle setup (not that I can think of anything better right now)

File: MoltenVKPackaging.xcodeproj/project.pbxproj (hunk 7 above)
Comment (mkrus) [reply MoltenVKPackaging.xcodeproj/project.pbxproj:282]: it was already there, just not added as a reference to the Xcode project

Comment (billhollings) [reply MoltenVKPackaging.xcodeproj/project.pbxproj:282]: Ah. Can you drag it into Xcode under Project Navigator->Scripts, please? That must have got overlooked when the script was created.

File: MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm [hunk 8]
```diff
@@ -1010,7 +1017,7 @@
 	addVkFormatDesc( D16_UNORM_S8_UINT, Invalid, Depth16Unorm_Stencil8, Invalid, Invalid, 1, 1, 3, DepthStencil );
 	addVkFormatDesc( D24_UNORM_S8_UINT, Depth24Unorm_Stencil8, Depth32Float_Stencil8, Invalid, Invalid, 1, 1, 4, DepthStencil );
 
-	addVkFormatDesc( X8_D24_UNORM_PACK32, Invalid, Depth24Unorm_Stencil8, Invalid, Invalid, 1, 1, 4, DepthStencil );
+    addVkFormatDesc( X8_D24_UNORM_PACK32, Invalid, Depth24Unorm_Stencil8, Invalid, Invalid, 1, 1, 4, DepthStencil );
```
Comment (billhollings) [inline MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm:1020]: I guess this is just leftover reformatting now?

File: MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm [hunk 9]
```diff
@@ -1321,8 +1328,8 @@
 	addMTLPixelFormatDesc    ( Depth32Float, None, DRM, DRFMR );
 	addMTLPixelFormatDesc    ( Stencil8, None, DRM, DRMR );
 	addMTLPixelFormatDesc    ( Depth24Unorm_Stencil8, Depth24_Stencil8, None, None );
-	addMTLPixelFormatDesc    ( Depth32Float_Stencil8, Depth32_Stencil8, DRM, DRFMR );
-	addMTLPixelFormatDesc    ( X24_Stencil8, Depth24_Stencil8, None, DRMR );
+    addMTLPixelFormatDesc    ( X24_Stencil8, Depth24_Stencil8, None, DRMR );
+    addMTLPixelFormatDesc    ( Depth32Float_Stencil8, Depth32_Stencil8, DRM, DRFMR );
```
Comment (billhollings) [inline MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm:1332]: Ditto?

File: MoltenVK/MoltenVK/Utility/MVKFoundation.h [hunk 10]
```diff
@@ -553,11 +553,10 @@ static void mvkRemoveAllOccurances(C& container, T val) {
 /** Selects and returns one of the values, based on the platform OS. */
 template<typename T>
 static constexpr const T& mvkSelectPlatformValue(const T& macOSVal, const T& iOSVal) {
-#if MVK_IOS_OR_TVOS
-	return iOSVal;
-#endif
 #if MVK_MACOS
 	return macOSVal;
+#else
+    return iOSVal;
```
Comment (billhollings) [inline MoltenVK/MoltenVK/Utility/MVKFoundation.h:559]: Does this work, or does this function need a rework? 

Are VisionOS values that might be used here the same as iOS values? So far, we're just using it for `MVKMTLFmtCaps`.

**Review by billhollings — COMMENTED** [review]
Just a few minor questions before approval.

File: MoltenVK/MoltenVK/Utility/MVKFoundation.h (hunk 10 above)
Comment (mkrus) [reply MoltenVK/MoltenVK/Utility/MVKFoundation.h:559]: might need rework later, so far focusing on build rather than functionality

File: MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm [hunk 11]
```diff
@@ -1329,8 +1336,8 @@
 	addMTLPixelFormatDesc    ( Depth32Float, None, DRM, DRFMR );
 	addMTLPixelFormatDesc    ( Stencil8, None, DRM, DRMR );
 	addMTLPixelFormatDesc    ( Depth24Unorm_Stencil8, Depth24_Stencil8, None, None );
-	addMTLPixelFormatDesc    ( Depth32Float_Stencil8, Depth32_Stencil8, DRM, DRFMR );
 	addMTLPixelFormatDesc    ( X24_Stencil8, Depth24_Stencil8, None, DRMR );
+	addMTLPixelFormatDesc    ( Depth32Float_Stencil8, Depth32_Stencil8, DRM, DRFMR );
```
Comment (billhollings) [inline MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm:1340]:
```suggestion
	addMTLPixelFormatDesc    ( Depth32Float_Stencil8, Depth32_Stencil8, DRM, DRFMR );
	addMTLPixelFormatDesc    ( X24_Stencil8, Depth24_Stencil8, None, DRMR );
```

**Review by billhollings — APPROVED** [review]
Thanks for the fixes. LGTM now.
